# Generated by Django 5.0.6 on 2024-06-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
